source	:rubygems

gem 'bundler', '1.7.12'
gem 'rake', '0.9.2.2'
gem 'watchr', '0.7'


gem 'bcat', '0.6.2'
gem 'aruba', '0.4.11'
gem 'cucumber', '1.2.1'
gem 'rake', '0.9.2.2'
gem 'rspec', '2.11.0'
gem 'activerecord', '3.2.2'
gem 'capybara', '2.0.0.beta2'
gem 'coffee-rails', '3.2.2'
gem 'cucumber-rails', '1.3.0'
gem 'database_cleaner', '0.8.0'
gem 'factory_girl', '3.5.0'
gem 'jquery-rails', '2.0.2'
gem 'launchy', '2.1.0' 

gem 'rails', '3.2.2'
gem 'rspec-rails', '2.11.0'
gem 'sass-rails', '3.2.5'
gem 'sqlite3', '1.3.6'
gem 'uglifier', '1.2.6'

gem 'childprocess', '0.3.4'
gem 'httparty', '0.8.3'
gem 'json', '1.8.2'
gem 'rack-test', '0.6.1'
gem 'service_manager', '0.6.4'
gem 'sinatra', '1.3.2'


